//HintName: TestApp.AppSettings.Settings.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable
using System;
using Everlong.Settings;

namespace TestApp;
partial class AppSettings : ISettingsRoot
{
  public static AppSettings Default
  {
    get
    {
      if (field is null)
      {
        field = new AppSettings();
        ((global::Everlong.Settings.ISettingsRoot)field).Initialize(new global::Everlong.Settings.NoOpSettingsStore());
      }

      return field;
    }
  }

  private ISettingsStore? _store;
  private PropertyBacker<int>? _fontSizeBacker;
  public partial int FontSize
  {
    get => _fontSizeBacker?.Value ?? 14;
    set
    {
      if (value < 10)
        value = 10;
      else if (value > 24)
        value = 24;
      value = CoerceFontSize(value);
      if (_fontSizeBacker!.TrySet(value))
      {
        OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs(nameof(FontSize)));
        OnFontSizeChanged(value);
      }
    }
  }

  private static partial int CoerceFontSize(int value);
  partial void OnFontSizeChanged(int value);
  /// <inheritdoc/>
  void ISettingsRoot.Initialize(ISettingsStore? store)
  {
    if (store is null && _store is null)
      throw new InvalidOperationException("Initialize must be called with a non-null store before it can be re-invoked.");
    if (store is not null)
      _store = store;
    ((ISettingsSection)this).Initialize(_store!, string.Empty);
  }

  /// <summary>
  /// Creates a <see cref = "global::Everlong.Settings.SettingsSnapshot{T}"/> containing a shadow copy of this
  /// settings object backed by a <see cref = "global::Everlong.Settings.CommittableSettingsStore"/>.
  /// Mutations on the shadow are buffered and can be committed or discarded atomically.
  /// </summary>
  /// <exception cref = "InvalidOperationException">Thrown when the settings have not been initialized yet.</exception>
  public SettingsSnapshot<AppSettings> Snapshot()
  {
    var store = new CommittableSettingsStore(this, _store ?? throw new InvalidOperationException("Cannot create a snapshot before the settings are initialized."));
    var shadow = new AppSettings();
    ((ISettingsRoot)shadow).Initialize(store);
    return new(shadow, store);
  }

  /// <inheritdoc/>
  void ISettingsSection.Initialize(ISettingsStore store, string keyPrefix)
  {
    _fontSizeBacker ??= new PropertyBacker<int>(keyPrefix, nameof(FontSize), 14);
    _fontSizeBacker.SetStore(store);
    if (_fontSizeBacker.GetInitialValue(14))
    {
      OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs(nameof(FontSize)));
      OnFontSizeChanged(_fontSizeBacker.Value);
    }
  }

  public event System.ComponentModel.PropertyChangedEventHandler? PropertyChanged;
  protected virtual void OnPropertyChanged(System.ComponentModel.PropertyChangedEventArgs args) => PropertyChanged?.Invoke(this, args);
}