//HintName: TestApp.AppSettings.Settings.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable
using System;
using Everlong.Settings;

namespace TestApp;
partial class AppSettings : ISettingsRoot
{
  public static AppSettings Default
  {
    get
    {
      if (field is null)
      {
        field = new AppSettings();
        ((global::Everlong.Settings.ISettingsRoot)field).Initialize(new global::Everlong.Settings.NoOpSettingsStore());
      }

      return field;
    }
  }

  private ISettingsStore? _store;
  private PropertyBacker<int>? _volumeBacker;
  public partial int Volume
  {
    get => _volumeBacker?.Value ?? 50;
    set
    {
      if (value < 0)
        value = 0;
      else if (value > 100)
        value = 100;
      if (_volumeBacker!.TrySet(value))
      {
        OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs(nameof(Volume)));
        OnVolumeChanged(value);
      }
    }
  }

  partial void OnVolumeChanged(int value);
  /// <inheritdoc/>
  void ISettingsRoot.Initialize(ISettingsStore? store)
  {
    if (store is null && _store is null)
      throw new InvalidOperationException("Initialize must be called with a non-null store before it can be re-invoked.");
    if (store is not null)
      _store = store;
    ((ISettingsSection)this).Initialize(_store!, string.Empty);
  }

  /// <summary>
  /// Creates a <see cref = "global::Everlong.Settings.SettingsSnapshot{T}"/> containing a shadow copy of this
  /// settings object backed by a <see cref = "global::Everlong.Settings.CommittableSettingsStore"/>.
  /// Mutations on the shadow are buffered and can be committed or discarded atomically.
  /// </summary>
  /// <exception cref = "InvalidOperationException">Thrown when the settings have not been initialized yet.</exception>
  public SettingsSnapshot<AppSettings> Snapshot()
  {
    var store = new CommittableSettingsStore(this, _store ?? throw new InvalidOperationException("Cannot create a snapshot before the settings are initialized."));
    var shadow = new AppSettings();
    ((ISettingsRoot)shadow).Initialize(store);
    return new(shadow, store);
  }

  /// <inheritdoc/>
  void ISettingsSection.Initialize(ISettingsStore store, string keyPrefix)
  {
    _volumeBacker ??= new PropertyBacker<int>(keyPrefix, nameof(Volume), 50);
    _volumeBacker.SetStore(store);
    if (_volumeBacker.GetInitialValue(50))
    {
      OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs(nameof(Volume)));
      OnVolumeChanged(_volumeBacker.Value);
    }
  }

  public event System.ComponentModel.PropertyChangedEventHandler? PropertyChanged;
  protected virtual void OnPropertyChanged(System.ComponentModel.PropertyChangedEventArgs args) => PropertyChanged?.Invoke(this, args);
}