//HintName: TestApp.AppSettings.Settings.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable
using System;
using Everlong.Settings;

namespace TestApp;
partial class AppSettings : ISettingsRoot
{
  public static AppSettings Default
  {
    get
    {
      if (field is null)
      {
        field = new AppSettings();
        ((global::Everlong.Settings.ISettingsRoot)field).Initialize(new global::Everlong.Settings.NoOpSettingsStore());
      }

      return field;
    }
  }

  private ISettingsStore? _store;
  private PropertyBacker<global::TestApp.Theme>? _colorThemeBacker;
  public partial global::TestApp.Theme ColorTheme
  {
    get => _colorThemeBacker?.Value ?? (global::TestApp.Theme)0;
    set
    {
      if (_colorThemeBacker!.TrySet(value))
      {
        OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs(nameof(ColorTheme)));
        OnColorThemeChanged(value);
      }
    }
  }

  partial void OnColorThemeChanged(global::TestApp.Theme value);
  /// <inheritdoc/>
  void ISettingsRoot.Initialize(ISettingsStore? store)
  {
    if (store is null && _store is null)
      throw new InvalidOperationException("Initialize must be called with a non-null store before it can be re-invoked.");
    if (store is not null)
      _store = store;
    ((ISettingsSection)this).Initialize(_store!, string.Empty);
  }

  /// <summary>
  /// Creates a <see cref = "global::Everlong.Settings.SettingsSnapshot{T}"/> containing a shadow copy of this
  /// settings object backed by a <see cref = "global::Everlong.Settings.CommittableSettingsStore"/>.
  /// Mutations on the shadow are buffered and can be committed or discarded atomically.
  /// </summary>
  /// <exception cref = "InvalidOperationException">Thrown when the settings have not been initialized yet.</exception>
  public SettingsSnapshot<AppSettings> Snapshot()
  {
    var store = new CommittableSettingsStore(this, _store ?? throw new InvalidOperationException("Cannot create a snapshot before the settings are initialized."));
    var shadow = new AppSettings();
    ((ISettingsRoot)shadow).Initialize(store);
    return new(shadow, store);
  }

  /// <inheritdoc/>
  void ISettingsSection.Initialize(ISettingsStore store, string keyPrefix)
  {
    _colorThemeBacker ??= new PropertyBacker<global::TestApp.Theme>(keyPrefix, nameof(ColorTheme), (global::TestApp.Theme)0);
    _colorThemeBacker.SetStore(store);
    if (_colorThemeBacker.GetInitialValue((global::TestApp.Theme)0))
    {
      OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs(nameof(ColorTheme)));
      OnColorThemeChanged(_colorThemeBacker.Value);
    }
  }

  public event System.ComponentModel.PropertyChangedEventHandler? PropertyChanged;
  protected virtual void OnPropertyChanged(System.ComponentModel.PropertyChangedEventArgs args) => PropertyChanged?.Invoke(this, args);
}