//HintName: TestApp.SoundSettings.Settings.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable
using System;
using Everlong.Settings;

namespace TestApp;
partial class SoundSettings : ISettingsSection
{
  private PropertyBacker<int>? _volumeBacker;
  public partial int Volume
  {
    get => _volumeBacker?.Value ?? 50;
    set
    {
      if (_volumeBacker!.TrySet(value))
      {
        OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs(nameof(Volume)));
        OnVolumeChanged(value);
      }
    }
  }

  partial void OnVolumeChanged(int value);
  /// <inheritdoc/>
  void ISettingsSection.Initialize(ISettingsStore store, string keyPrefix)
  {
    _volumeBacker ??= new PropertyBacker<int>(keyPrefix, nameof(Volume), 50);
    _volumeBacker.SetStore(store);
    if (_volumeBacker.GetInitialValue(50))
    {
      OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs(nameof(Volume)));
      OnVolumeChanged(_volumeBacker.Value);
    }
  }

  public event System.ComponentModel.PropertyChangedEventHandler? PropertyChanged;
  protected virtual void OnPropertyChanged(System.ComponentModel.PropertyChangedEventArgs args) => PropertyChanged?.Invoke(this, args);
}