namespace Everlong.Settings.Generators.Constants;

internal static class Conventions
{
  internal const string ViewModelSuffix = "ViewModel";
  internal const string ViewSuffix = "View";
  internal const string PageSuffix = "Page";
  internal const string ModelSuffix = "Model";
  internal const string ViewsNamespaceSuffix = ".Views";
  internal const string ViewModelsNamespaceSuffix = ".ViewModels";

  internal const string RouteSuffix = "Route";
  internal const string Indentation = "  ";

  internal const string GeneratorSuffix = ".g.cs";
  internal const string AutoGeneratedHeader = "// <auto-generated/>\n#pragma warning disable\n#nullable enable\n\n";

  internal const string InjectedFieldPrefix = "__injected_";
  internal const string AuthDescriptor = "AuthDescriptor";

  internal const string DialogCompletionSource = "DialogCompletionSource";
  internal const string TaskCompletionSource = "TaskCompletionSource";
}
